# Generated by Django 4.2.7 on 2025-10-26 09:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الخط (Row)')),
                ('column', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='العمود (Column)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'موقع',
                'verbose_name_plural': 'الأماكن',
                'ordering': ['warehouse', 'row', 'column'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المستودع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('rows_count', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الصفوف')),
                ('columns_count', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الأعمدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مستودع',
                'verbose_name_plural': 'المستودعات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='رقم المنتج')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='الفئة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory_app.location', verbose_name='الموقع')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['product_number'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory_app.warehouse', verbose_name='المستودع'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('added', 'إضافة منتج'), ('updated', 'تعديل منتج'), ('deleted', 'حذف منتج'), ('quantity_taken', 'سحب كمية'), ('quantity_added', 'إضافة كمية'), ('location_assigned', 'ربط بالمواقع'), ('location_removed', 'إلغاء ربط موقع')], max_length=20, verbose_name='العملية')),
                ('product_number', models.CharField(max_length=50, verbose_name='رقم المنتج')),
                ('quantity_before', models.IntegerField(blank=True, null=True, verbose_name='الكمية قبل')),
                ('quantity_after', models.IntegerField(blank=True, null=True, verbose_name='الكمية بعد')),
                ('quantity_change', models.IntegerField(default=0, verbose_name='التغيير')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('user', models.CharField(blank=True, default='System', max_length=100, verbose_name='المستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='inventory_app.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'سجل عمليات',
                'verbose_name_plural': 'سجلات العمليات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('warehouse', 'row', 'column')},
        ),
    ]
