# Generated by Django 4.2.7 on 2025-10-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True, verbose_name='تاريخ التقرير')),
                ('hijri_date', models.CharField(blank=True, max_length=100, verbose_name='التاريخ الهجري')),
                ('products_added', models.IntegerField(default=0, verbose_name='منتجات مضافة')),
                ('products_updated', models.IntegerField(default=0, verbose_name='منتجات محدثة')),
                ('products_deleted', models.IntegerField(default=0, verbose_name='منتجات محذوفة')),
                ('quantities_taken', models.IntegerField(default=0, verbose_name='كميات مسحوبة')),
                ('locations_assigned', models.IntegerField(default=0, verbose_name='مواقع مخصصة')),
                ('total_added', models.IntegerField(default=0, verbose_name='إجمالي الكميات المضافة')),
                ('total_removed', models.IntegerField(default=0, verbose_name='إجمالي الكميات المسحوبة')),
                ('report_data', models.JSONField(default=dict, verbose_name='بيانات التقرير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تقرير يومي محفوظ',
                'verbose_name_plural': 'التقارير اليومية المحفوظة',
                'ordering': ['-report_date'],
            },
        ),
    ]
