# Generated by Django 4.2.7 on 2025-10-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_dailyreportarchive'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='inventory_a_created_a207f9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='inventory_a_action_22e5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['product'], name='inventory_a_product_39513e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['product_number'], name='inventory_a_product_e67a07_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreportarchive',
            index=models.Index(fields=['-report_date'], name='inventory_a_report__0296a1_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['warehouse', 'row', 'column'], name='inventory_a_warehou_eb4247_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_active'], name='inventory_a_is_acti_fd89dd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_number'], name='inventory_a_product_25bb19_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='inventory_a_name_53adc3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['location'], name='inventory_a_locatio_921405_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='inventory_a_categor_1f5386_idx'),
        ),
    ]
