# Generated by Django 4.2.7 on 2025-10-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportarchive',
            name='is_auto_saved',
            field=models.BooleanField(default=False, verbose_name='حفظ تلقائي'),
        ),
    ]
