# Generated by Django 4.2.7 on 2025-10-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_dailyreportarchive_is_auto_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='رقم الطلبية')),
                ('products_data', models.JSONField(default=list, verbose_name='بيانات المنتجات')),
                ('total_products', models.IntegerField(default=0, verbose_name='عدد المنتجات')),
                ('total_quantities', models.IntegerField(default=0, verbose_name='إجمالي الكميات المسحوبة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('user', models.CharField(blank=True, default='System', max_length=100, verbose_name='المستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'طلب مسحوب',
                'verbose_name_plural': 'الطلبات المسحوبة',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='inventory_a_created_e339fd_idx'), models.Index(fields=['order_number'], name='inventory_a_order_n_f383f7_idx')],
            },
        ),
    ]
