# Generated by Django 4.2.7 on 2025-11-02 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory_app', '0006_order_recipient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'مسؤول'), ('staff', 'موظف')], default='staff', max_length=10, verbose_name='نوع المستخدم')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='آخر نشاط')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخر IP تسجيل دخول')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف مستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_type'], name='inventory_a_user_ty_144396_idx'), models.Index(fields=['is_active'], name='inventory_a_is_acti_ea39d5_idx'), models.Index(fields=['-last_activity'], name='inventory_a_last_ac_720a7d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('product_added', 'إضافة منتج'), ('product_updated', 'تعديل منتج'), ('product_deleted', 'حذف منتج'), ('product_viewed', 'عرض منتج'), ('order_created', 'إنشاء طلب'), ('order_viewed', 'عرض طلب'), ('order_deleted', 'حذف طلب'), ('location_assigned', 'ربط موقع'), ('location_updated', 'تعديل موقع'), ('quantity_taken', 'سحب كمية'), ('quantity_reset', 'تصفير كميات'), ('backup_created', 'إنشاء نسخة احتياطية'), ('backup_restored', 'استعادة نسخة احتياطية'), ('data_deleted', 'حذف بيانات'), ('user_created', 'إنشاء مستخدم'), ('user_updated', 'تعديل مستخدم'), ('user_deleted', 'حذف مستخدم'), ('page_viewed', 'عرض صفحة'), ('export_pdf', 'تصدير PDF'), ('export_excel', 'تصدير Excel'), ('search_performed', 'بحث'), ('other', 'أخرى')], max_length=50, verbose_name='نوع العملية')),
                ('description', models.CharField(max_length=500, verbose_name='الوصف')),
                ('object_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الكائن')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='معرف الكائن')),
                ('object_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الكائن')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='التفاصيل')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='الموقع')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='رابط الصفحة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل نشاط مستخدم',
                'verbose_name_plural': 'سجلات أنشطة المستخدمين',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='inventory_a_created_961d23_idx'), models.Index(fields=['user', '-created_at'], name='inventory_a_user_id_8dae5e_idx'), models.Index(fields=['action'], name='inventory_a_action_e04115_idx'), models.Index(fields=['object_type', 'object_id'], name='inventory_a_object__11fd58_idx'), models.Index(fields=['ip_address'], name='inventory_a_ip_addr_2b5840_idx')],
            },
        ),
    ]
