# Generated by Django 4.2.7 on 2025-11-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0007_userprofile_useractivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='رقم المرتجع')),
                ('products_data', models.JSONField(default=list, verbose_name='بيانات المنتجات المرتجعة')),
                ('total_products', models.IntegerField(default=0, verbose_name='عدد المنتجات')),
                ('total_quantities', models.IntegerField(default=0, verbose_name='إجمالي الكميات المرتجعة')),
                ('return_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='سبب الإرجاع')),
                ('returned_by', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المرسل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('user', models.CharField(blank=True, default='System', max_length=100, verbose_name='المستخدم الذي أضاف المرتجع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مرتجع',
                'verbose_name_plural': 'المرتجعات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='inventory_a_created_dee8a0_idx'), models.Index(fields=['return_number'], name='inventory_a_return__2f2cfa_idx')],
            },
        ),
    ]
