# Generated by Django 4.2.7 on 2025-11-08 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0008_productreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carton_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد الكراتين'),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_per_carton',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الحبات في الكرتون'),
        ),
    ]
