# Generated by Django 4.2.7 on 2025-11-09 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0009_product_carton_count_product_qty_per_carton'),
    ]

    operations = [
        # فقط إضافة حقل الصورة - باقي الحقول موجودة بالفعل
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة المنتج'),
        ),
    ]
