# Generated by Django 4.2.7 on 2025-11-09 04:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0010_product_barcode_product_dozens_per_carton_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الحاوية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('color', models.CharField(default='#667eea', max_length=7, verbose_name='اللون')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'حاوية',
                'verbose_name_plural': 'الحاويات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory_app.container', verbose_name='الحاوية'),
        ),
    ]
