# Generated by Django 4.2.7 on 2025-11-17 02:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0021_client_product_barcode_product_dozens_per_carton_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='يجب أن يكون رقم الهاتف أرقام فقط من 8 إلى 15 رقم. يمكن أن يبدأ بعلامة +.', regex='^\\+?[0-9]{8,15}$')], verbose_name='رقم الهاتف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'أشخاص',
                'ordering': ['-created_at'],
            },
        ),
        # الحقول موجودة مسبقاً في قاعدة البيانات، لذلك لا نضيفها هنا
        migrations.CreateModel(
            name='PersonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='person_images/', verbose_name='الصورة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory_app.person', verbose_name='الشخص')),
            ],
            options={
                'verbose_name': 'صورة',
                'verbose_name_plural': 'صور',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
