# Generated by Django 4.2.7 on 2025-11-23 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0022_person_product_barcode_product_dozens_per_carton_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الباركود'),
        ),
        migrations.AddField(
            model_name='product',
            name='dozens_per_carton',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الدرزنات في الكرتون'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='رابط الصورة'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock_threshold',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الحد الأدنى للمخزون'),
        ),
        migrations.AddField(
            model_name='product',
            name='pcs_per_dozen',
            field=models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الحبات في الدرزن'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر'),
        ),
        migrations.AddField(
            model_name='product',
            name='store_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='كمية المحل'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='كمية المستودع'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PersonImage',
        ),
    ]
