# Generated by Django 4.2.7 on 2025-12-28 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory_app', '0024_product_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقرير')),
                ('period_hours', models.IntegerField(default=6, verbose_name='الفترة (ساعات)')),
                ('total_orders', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('insights_data', models.JSONField(default=list, verbose_name='الرؤى والملاحظات')),
            ],
            options={
                'verbose_name': 'تقرير ذكي',
                'verbose_name_plural': 'التقارير الذكية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='clientimage',
            name='client',
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='container',
            options={},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productreturn',
            options={},
        ),
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='inventory_a_created_a207f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='inventory_a_action_22e5bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='inventory_a_product_39513e_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='inventory_a_product_e67a07_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='inventory_a_warehou_eb4247_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='inventory_a_is_acti_fd89dd_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='inventory_a_created_e339fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='inventory_a_order_n_f383f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='inventory_a_product_25bb19_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='inventory_a_name_53adc3_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='inventory_a_locatio_921405_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='inventory_a_categor_1f5386_idx',
        ),
        migrations.RemoveIndex(
            model_name='productreturn',
            name='inventory_a_created_dee8a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='productreturn',
            name='inventory_a_return__2f2cfa_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivitylog',
            name='inventory_a_created_961d23_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivitylog',
            name='inventory_a_user_id_8dae5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivitylog',
            name='inventory_a_action_e04115_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivitylog',
            name='inventory_a_object__11fd58_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivitylog',
            name='inventory_a_ip_addr_2b5840_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='inventory_a_user_ty_144396_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='inventory_a_is_acti_ea39d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='inventory_a_last_ac_720a7d_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_app.product'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='product_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='product_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='quantity_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='quantity_before',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='quantity_change',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='container',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='container',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='column',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='row',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.warehouse'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='products_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_products',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_quantities',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='carton_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_app.container'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dozens_per_carton',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory_app.location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock_threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcs_per_dozen',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty_per_carton',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='store_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouse_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='products_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='return_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='return_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='returned_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='total_products',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='total_quantities',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='object_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='object_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='columns_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='rows_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientImage',
        ),
    ]
