# Generated by Django 4.2.7 on 2025-12-28 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0025_aiinsightlog_remove_clientimage_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='inventory_app.product'),
        ),
    ]
