# Generated by Django 4.2.7 on 2025-12-28 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0026_alter_auditlog_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='carton_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty_per_carton',
        ),
    ]
