# Generated by Django 4.2.7 on 2025-12-28 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0027_remove_product_carton_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pcs_per_dozen',
        ),
    ]
