# Generated by Django 4.2.7 on 2025-12-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0031_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'مسؤول'), ('staff', 'موظف'), ('viewer', 'مشاهد')], max_length=10),
        ),
    ]
