# Generated by Django 4.2.7 on 2025-12-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0032_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.IntegerField()),
                ('backup_data', models.JSONField(default=dict)),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تحديث'), ('delete', 'حذف')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hash_signature', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='AIInsightLog',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='securebackup',
            index=models.Index(fields=['table_name', 'record_id'], name='inventory_a_table_n_66062c_idx'),
        ),
        migrations.AddIndex(
            model_name='securebackup',
            index=models.Index(fields=['timestamp'], name='inventory_a_timesta_fa4ee8_idx'),
        ),
    ]
