# Generated by Django 4.2.7 on 2026-04-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0034_alter_product_container'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=10, unique=True, verbose_name='رقم الفاتورة')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(blank=True, max_length=50, verbose_name='رقم الهاتف')),
                ('customer_address', models.TextField(blank=True, verbose_name='العنوان')),
                ('issuer', models.CharField(blank=True, max_length=200, verbose_name='المخرج')),
                ('products_data', models.JSONField(default=list, verbose_name='بيانات المنتجات')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي قبل الضريبة')),
                ('tax_applied', models.BooleanField(default=False, verbose_name='تم تطبيق الضريبة')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الضريبة')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الخصم')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي النهائي')),
                ('total_text', models.CharField(blank=True, max_length=500, verbose_name='الإجمالي كتابةً')),
                ('user', models.CharField(max_length=100, verbose_name='المستخدم')),
                ('invoice_date', models.DateField(verbose_name='تاريخ الفاتورة')),
                ('hijri_date', models.CharField(blank=True, max_length=80, verbose_name='التاريخ الهجري')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'ordering': ['-created_at'],
            },
        ),
    ]
